name: mapbox_gl
description: A Flutter plugin for integrating Mapbox Maps inside a Flutter application on Android, iOS and web platfroms.
version: 0.17.0
publish_to: https://onepub.dev/api/jauppsdavu/
repository: https://github.com/calqi/flutter_mapbox.git

dependencies:
  flutter:
    sdk: flutter
  mapbox_gl_platform_interface:
      hosted: https://onepub.dev/api/jauppsdavu/
      version:  ^0.17.0
  mapbox_gl_web:
      hosted: https://onepub.dev/api/jauppsdavu/
      version:  ^0.17.0

  collection: ^1.15.0


flutter:
  plugin:
    platforms:
      android:
        package: com.mapbox.mapboxgl
        pluginClass: MapboxMapsPlugin
      ios:
        pluginClass: MapboxMapsPlugin
      web:
        default_package: mapbox_gl_web

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.0'
