name: mapbox_gl_platform_interface
description: A common platform interface for the mapbox_gl plugin.
version: 0.17.0
homepage: https://github.com/tobrun/flutter-mapbox-gl
publish_to: https://onepub.dev/api/jauppsdavu/

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.0'
