name: mapbox_gl_web
description: Web platform implementation of mapbox_gl
version: 0.17.1
homepage: https://github.com/tobrun/flutter-mapbox-gl
publish_to: https://onepub.dev/api/jauppsdavu/

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MapboxMapPlugin
        fileName: mapbox_gl_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7
  js: ^0.6.3
  mapbox_gl_platform_interface:
    hosted: https://onepub.dev/api/jauppsdavu/
    version:  ^0.17.0

  mapbox_gl_dart: ^0.2.1
  image: '>=3.0.0 <5.0.0'



dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.0'
